# -*- coding: utf-8 -*-
"""1.0-test-noise-reduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/timsainb/noisereduce/blob/master/notebooks/1.0-test-noise-reduction.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext autoreload
# %autoreload 2
# %env CUDA_VISIBLE_DEVICES=3


"""# Test noise reduction algorithm and view steps of algorithm"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline




import noisereduce as nr
import librosa


def reduce_noise(file_location, noise_file_location):
    """### Load data"""

    data, rate = librosa.load(file_location)
    # print(rate, data)
    # fig, ax = plt.subplots(figsize=(20,3))
    # ax.plot(data)

    """### add noise"""
    noise_data, noise_rate = librosa.load(noise_file_location)


    """### add noise to data"""

    snr = 2  # signal to noise ratio
    noise_clip = noise_data/snr
    audio_clip_cafe = data + noise_clip

    """### Stationary remove noise"""

    reduced_noise = nr.reduce_noise(
        y=audio_clip_cafe, sr=rate, y_noise=noise_clip, n_std_thresh_stationary=1.5, stationary=True)

    return reduced_noise, rate